apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-03-13T03:24:15Z
  generation: 1
  labels:
    run: go-service1
  name: go-service1
  namespace: default
  resourceVersion: "391075"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/go-service1
  uid: 7aa58473-453f-11e9-9d06-42010a920246
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: go-service1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: go-service1
    spec:
      containers:
      - env:
        - name: PORT
          value: 0.0.0.0:8000
        image: thementos/go-service1
        imagePullPolicy: Always
        name: go-service1
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-03-13T03:24:21Z
    lastUpdateTime: 2019-03-13T03:24:21Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-03-13T03:24:15Z
    lastUpdateTime: 2019-03-13T03:24:21Z
    message: ReplicaSet "go-service1-5b7796ffc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
