apiVersion: v1
kind: Service
metadata:
  name: go-service1
  labels:
    app: go-service1
spec:
  type: NodePort
  ports:
    - name: go-service1-http
      port: 8080
      targetPort: 8000
      nodePort: 31000
      protocol: TCP
  selector:
    app: go-service1